export const dicts = {
    'Harry Potter and the Sorcerer`s Stone':['The Hunger Games \n','To Kill a Mockingbird \n','The Fault in Our Stars \n','1984 \n','Pride and Prejudice'], 
    'The Hunger Games':['Harry Potter and the Sorcerer`s Stone \n','To Kill a Mockingbird \n','The Fault in Our Stars \n','1984 \n','Pride and Prejudice'], 
    'Twilight':['The Great Gatsby \n','The Catcher in the Rye \n','Animal Farm \n','Angels & Demons \n','Lord of the Flies'], 
    'To Kill a Mockingbird':['The Fault in Our Stars \n','1984 \n','Pride and Prejudice \n','The Hobbit, or There and Back Again \n','Divergent'], 
    'The Great Gatsby':['Animal Farm \n','The Catcher in the Rye \n','Angels & Demons \n','Twilight \n','Lord of the Flies'], 
    'The Fault in Our Stars':['1984 \n','Pride and Prejudice \n','Divergent \n','The Hobbit, or There and Back Again \n','The Diary of a Young Girl'], 
    '1984':['Pride and Prejudice \n','Divergent \n','The Hobbit, or There and Back Again \n','The Diary of a Young Girl \n','The Fault in Our Stars'], 
    'Pride and Prejudice':['The Hobbit, or There and Back Again \n','Divergent \n','1984 \n','The Diary of a Young Girl \n','Harry Potter and the Chamber of Secrets'], 
    'Divergent':['The Hobbit, or There and Back Again \n','Pride and Prejudice \n','The Diary of a Young Girl \n','1984 \n','The Girl with the Dragon Tattoo'], 
    'The Hobbit, or There and Back Again':['Pride and Prejudice \n','Divergent \n','1984 \n','The Diary of a Young Girl \n','Catching Fire'], 
    'Harry Potter and the Deathly Hallows':['Harry Potter and the Prisoner of Azkaban \n','Harry Potter and the Goblet of Fire \n','Harry Potter and the Half-Blood Prince \n','Harry Potter and the Order of the Phoenix \n','Harry Potter and the Chamber of Secrets'], 
    'Harry Potter and the Prisoner of Azkaban':['Harry Potter and the Deathly Hallows \n','Harry Potter and the Goblet of Fire \n','Harry Potter and the Chamber of Secrets \n','Harry Potter and the Order of the Phoenix \n','Harry Potter and the Half-Blood Prince'], 
    'The Diary of a Young Girl':['The Girl with the Dragon Tattoo \n','Divergent \n','The Hobbit, or There and Back Again \n','Pride and Prejudice \n','Catching Fire'], 
    'Animal Farm':['Angels & Demons \n','The Catcher in the Rye \n','The Girl on the Train \n','The Alchemist \n','Lord of the Flies'], 
    'The Catcher in the Rye':['Angels & Demons \n','Animal Farm \n','Lord of the Flies \n','The Alchemist \n','The Girl on the Train'], 
    'Harry Potter and the Chamber of Secrets':['Harry Potter and the Order of the Phoenix \n','Harry Potter and the Goblet of Fire \n','Harry Potter and the Prisoner of Azkaban \n','Catching Fire \n','The Hobbit, or There and Back Again'], 
    'Angels & Demons':['Animal Farm \n','The Catcher in the Rye \n','The Girl on the Train \n','The Alchemist \n','Lord of the Flies'], 
    'The Girl with the Dragon Tattoo':['The Diary of a Young Girl \n','Gone Girl \n','Divergent \n','Mockingjay \n','Catching Fire'], 
    'Harry Potter and the Goblet of Fire':['Harry Potter and the Half-Blood Prince \n','Harry Potter and the Order of the Phoenix \n','Harry Potter and the Prisoner of Azkaban \n','Harry Potter and the Deathly Hallows \n','Harry Potter and the Chamber of Secrets'], 
    'Catching Fire':['The Kite Runner \n','The Fellowship of the Ring \n','The Girl with the Dragon Tattoo \n','Harry Potter and the Chamber of Secrets \n','The Hobbit, or There and Back Again'], 
    'Harry Potter and the Order of the Phoenix':['Harry Potter and the Goblet of Fire \n','Harry Potter and the Half-Blood Prince \n','Harry Potter and the Chamber of Secrets \n','Harry Potter and the Prisoner of Azkaban \n','The Help'], 
    'Harry Potter and the Half-Blood Prince':['Harry Potter and the Goblet of Fire \n','Harry Potter and the Order of the Phoenix \n','The Help \n','Harry Potter and the Prisoner of Azkaban \n','Harry Potter and the Deathly Hallows'], 
    'The Kite Runner':['Catching Fire \n','The Fellowship of the Ring \n','The Lion, the Witch and the Wardrobe \n','The Girl with the Dragon Tattoo \n','Harry Potter and the Chamber of Secrets'], 
    'The Fellowship of the Ring':['The Kite Runner \n','Catching Fire \n','The Help \n','Harry Potter and the Order of the Phoenix \n','The Lion, the Witch and the Wardrobe'], 
    'Mockingjay':['Gone Girl \n','The Girl with the Dragon Tattoo \n','The Lion, the Witch and the Wardrobe \n','The Diary of a Young Girl \n','Catching Fire'], 
    'Gone Girl':['Mockingjay \n','The Girl with the Dragon Tattoo \n','The Lion, the Witch and the Wardrobe \n','The Diary of a Young Girl \n','The Kite Runner'], 
    'Lord of the Flies':['Romeo and Juliet \n','Fifty Shades of Grey \n','The Lovely Bones \n','The Alchemist \n','The Da Vinci Code'], 
    'The Help':['A Game of Thrones \n','The Fellowship of the Ring \n','Harry Potter and the Order of the Phoenix \n','Harry Potter and the Half-Blood Prince \n','The Book Thief'], 
    'The Lion, the Witch and the Wardrobe':['The Lightning Thief \n','The Kite Runner \n','Gone Girl \n','The Fellowship of the Ring \n','The Giver'], 
    'The Girl on the Train':['The Alchemist \n','Of Mice and Men \n','The Da Vinci Code \n','The Lovely Bones \n','Romeo and Juliet'], 
    'The Alchemist':['The Girl on the Train \n','The Lovely Bones \n','Of Mice and Men \n','The Da Vinci Code \n','Romeo and Juliet'], 
    'Romeo and Juliet':['The Lovely Bones \n','Fifty Shades of Grey \n','Lord of the Flies \n','The Da Vinci Code \n','The Alchemist'], 
    'The Lovely Bones':['The Da Vinci Code \n','Of Mice and Men \n','Romeo and Juliet \n','The Alchemist \n','The Girl on the Train'], 
    'A Game of Thrones':['The Help \n','The Book Thief \n','The Fellowship of the Ring \n','The Lightning Thief \n','Harry Potter and the Half-Blood Prince'], 
    'The Lightning Thief':['The Lion, the Witch and the Wardrobe \n','The Book Thief \n','The Giver \n','Memoirs of a Geisha \n','The Fellowship of the Ring'], 
    'Fifty Shades of Grey':['Romeo and Juliet \n','Lord of the Flies \n','The Lovely Bones \n','The Da Vinci Code \n','Of Mice and Men'], 
    'Of Mice and Men':['The Da Vinci Code \n','The Lovely Bones \n','The Alchemist \n','The Girl on the Train \n','Romeo and Juliet'], 
    'The Da Vinci Code':['Of Mice and Men \n','The Lovely Bones \n','The Alchemist \n','The Girl on the Train \n','Romeo and Juliet'], 
    'The Book Thief':['A Game of Thrones \n','The Lightning Thief \n','The Help \n','The Lion, the Witch and the Wardrobe \n','The Little Prince'], 
    'The Giver':['Memoirs of a Geisha \n','Little Women \n','Jane Eyre \n','City of Bones \n','The Handmaid`s Tale'], 
    'Memoirs of a Geisha':['The Giver \n','Little Women \n','Jane Eyre \n','City of Bones \n','The Handmaid`s Tale'], 
    'Little Women':['City of Bones \n','Memoirs of a Geisha \n','Jane Eyre \n','The Giver \n','The Handmaid`s Tale'], 
    'Fahrenheit 451':['The Time Traveler`s Wife \n','Brave New World \n','Eragon \n','Of Mice and Men \n','Life of Pi'], 
    'Jane Eyre':['City of Bones \n','Memoirs of a Geisha \n','Little Women \n','The Giver \n','The Handmaid`s Tale'], 
    'City of Bones':['Little Women \n','Jane Eyre \n','Memoirs of a Geisha \n','The Handmaid`s Tale \n','The Giver'], 
    'The Time Traveler`s Wife':['Fahrenheit 451 \n','Brave New World \n','Eragon \n','Life of Pi \n','The Golden Compass'], 
    'Eat, Pray, Love':['New Moon \n','Eclipse \n','Breaking Dawn \n','Fifty Shades of Grey \n','Frankenstein: The 1818 Text'], 
    'New Moon':['Eat, Pray, Love \n','Eclipse \n','Breaking Dawn \n','Fifty Shades of Grey \n','Allegiant'], 
    'The Handmaid`s Tale':['Water for Elephants \n','The Notebook \n','Charlotte`s Web \n','City of Bones \n','Jane Eyre'], 
    'Brave New World':['The Time Traveler`s Wife \n','The Golden Compass \n','Eragon \n','Life of Pi \n','Fahrenheit 451'],     
      
  };