export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST'
export const BOOK_LIST_SUCESS = 'BOOK_LIST_SUCESS'
export const BOOK_LIST_FAIL = 'BOOK_LIST_FAIL'

export const BOOK_DATA_REQUEST = 'BOOK_DATA_REQUEST'
export const BOOK_DATA_SUCESS = 'BOOK_DATA_SUCESS'
export const BOOK_DATA_FAIL = 'BOOK_DATA_FAIL'