export const GENRE_LIST_REQUEST = 'GENRE_LIST_REQUEST'
export const GENRE_LIST_SUCESS = 'GENRE_LIST_SUCESS'
export const GENRE_LIST_FAIL = 'GENRE_LIST_FAIL'

export const GENRE_USER_REQUEST = 'GENRE_USER__REQUEST'
export const GENRE_USER_SUCESS = 'GENRE_USER_SUCESS'
export const GENRE_USER_FAIL = 'GENRE_USER_FAIL'

export const  GENRE_UPDATE_REQUEST = 'GENRE_UPDATE_REQUEST'
export const  GENRE_UPDATE_SUCESS = 'GENRE_UPDATE_SUCESS'
export const  GENRE_UPDATE_FAIL = 'GENRE_UPDATE_FAIL'