export const BOOK_HISTORY_ADD_REQUEST = 'BOOK_HISTORY_ADD_REQUEST'
export const BOOK_HISTORY_ADD_SUCESS = 'BOOK_HISTORY_ADD_SUCESS'
export const BOOK_HISTORY_ADD_FAIL = 'BOOK_HISTORY_ADD_FAIL'

export const BOOK_HISTORY_GET_REQUEST = 'BOOK_HISTORY_GET_REQUEST'
export const BOOK_HISTORY_GET_SUCESS = 'BOOK_HISTORY_GET_SUCCESS'
export const BOOK_HISTORY_GET_FAIL= 'BOOK_HISTORY_GET_FAIL'

export const BOOK_HISTORY_RETURN_REQUEST = 'BOOK_HISTORY_RETURN_REQUEST'
export const BOOK_HISTORY_RETURN_SUCESS = 'BOOK_HISTORY_RETURN_SUCESS'
export const BOOK_HISTORY_RETURN_FAIL= 'BOOK_HISTORY_RETURN_FAIL'

