export const USER_ADD_REQUEST = 'USER_ADD_REQUEST'
export const USER_ADD_SUCESS = 'USER_ADD_SUCESS'
export const USER_ADD_FAIL = 'USER_ADD_FAIL'


export const USER_GET_REQUEST = 'USER_GET_REQUEST'
export const USER_GET_SUCESS = 'USER_GET_SUCESS'
export const USER_GET_FAIL = 'USER_GET_FAIL'



export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCESS = 'USER_UPDATE_SUCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_SUCESS'


export const USER_RECOMENDATIONS_REQUEST = 'USER_RECOMENDATIONS_REQUEST'
export const USER_RECOMENDATIONS_SUCESS = 'USER_RECOMENDATIONS_SUCESS'
export const USER_RECOMENDATIONS_FAIL = 'USER_RECOMENDATIONS_SUCESS'