# Generated by Django 4.1.2 on 2022-10-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Book_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Availability', models.IntegerField(blank=True, default=0, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('NumberReviews', models.IntegerField(blank=True, null=True)),
                ('ImgSource', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('Author_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Author_Name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookReaders',
            fields=[
                ('Reader_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('FireBaseAuth', models.CharField(blank=True, max_length=255, null=True)),
                ('Age', models.CharField(blank=True, max_length=10, null=True)),
                ('Sex', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('Genre_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Genre_Name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWantedBooks',
            fields=[
                ('Order_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Book_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.book')),
                ('Reader_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bookreaders')),
            ],
        ),
        migrations.CreateModel(
            name='UserGenre',
            fields=[
                ('Order_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Genre_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.genre')),
                ('Reader_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bookreaders')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('AllReviews_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Review', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('Book_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.book')),
                ('Reader_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bookreaders')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('AllRenatls_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Date_Taken', models.DateTimeField(auto_now_add=True)),
                ('Returned', models.BooleanField(null=True)),
                ('Book_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.book')),
                ('Reader_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bookreaders')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bookauthor'),
        ),
        migrations.AddField(
            model_name='book',
            name='Genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.genre'),
        ),
    ]
