# Generated by Django 4.1.2 on 2022-10-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Returned',
            field=models.BooleanField(default=False),
        ),
    ]
