# Generated by Django 4.1.2 on 2022-10-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_history_returned'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookGenres',
            fields=[
                ('NrGenres', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Book_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.book')),
                ('Genre_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.genre')),
            ],
        ),
    ]
