# Generated by Django 4.1.2 on 2022-10-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_bookgenres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Genre',
        ),
    ]
