# Generated by Django 4.1.2 on 2022-10-30 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_bookauthor_author_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreShort',
            fields=[
                ('Genre_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Genre_Name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usergenre',
            name='Genre_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.genreshort'),
        ),
    ]
