# Generated by Django 4.1.2 on 2022-10-31 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_genreshort_alter_usergenre_genre_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmRecomendations',
            fields=[
                ('NrRecomendations', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Alogritm_ID', models.IntegerField(blank=True, null=True)),
                ('Book_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.book')),
                ('Reader_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bookreaders')),
            ],
        ),
    ]
