# Generated by Django 4.1.2 on 2022-11-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_offtop_recomendations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offtop_recomendations',
            old_name='ROW_ID',
            new_name='Row_ID',
        ),
    ]
