# Generated by Django 4.1.2 on 2022-12-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_row_id_offtop_recomendations_row_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offtop_recomendations',
            old_name='Row_ID',
            new_name='Alogritm_ID',
        ),
    ]
