# Generated by Django 4.1.2 on 2022-11-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='Books',
            new_name='Books1',
        ),
        migrations.AddField(
            model_name='userreview',
            name='Books2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
